// Map system with 50 unique maps featuring different environments, enemies, and effects
import { GAME_CONFIG } from './constants';

// Terrain type defines how the map is rendered
export type TerrainType = 
  | 'cave'           // Both ceiling and floor (classic)
  | 'surface'        // Only floor, open sky
  | 'ceiling'        // Only ceiling, open bottom (no floor, no civilians/ground enemies)
  | 'openSpace'      // No terrain at all (space)
  | 'city'           // Floor with tall buildings/skyscrapers
  | 'mixed';         // Sections that switch between types

export interface MapTheme {
  id: number;
  name: string;
  environment: 'space' | 'planet' | 'asteroid' | 'nebula' | 'industrial' | 'ice' | 'lava' | 'alien' | 'city' | 'ocean';
  
  // Visual settings
  backgroundColor1: string;
  backgroundColor2: string;
  backgroundColor3: string;
  terrainColor: string;
  terrainMidColor: string;
  terrainGlowColor: string;
  structureColor: string;
  
  // Atmospheric effects
  hasFog: boolean;
  fogColor: string;
  fogDensity: number;
  hasHaze: boolean;
  hazeColor: string;
  hasNebula: boolean;
  nebulaColors: string[];
  hasAurora: boolean;
  auroraColors: string[];
  
  // Terrain settings
  hasTerrain: boolean;  // false = open space (legacy, use terrainType instead)
  terrainType?: TerrainType; // NEW: defines terrain layout - optional for backwards compatibility
  terrainMinHeight: number;
  terrainMaxHeight: number;
  structureChance: number;
  structureTypes: ('building' | 'pipe' | 'tower' | 'crystal' | 'rock' | 'spire' | 'skyscraper' | 'antenna' | 'dome' | 'waterfall' | 'lavafall')[];
  hasHazardousTerrain?: boolean; // Terrain causes damage on collision
  hasFallingDebris?: boolean; // Rocks/debris fall from above
  debrisType?: 'rock' | 'ice' | 'lava' | 'metal'; // Type of falling debris
  
  // Moving obstacles
  hasMovingObstacles?: boolean;
  obstacleType?: 'gates' | 'pistons' | 'lasers' | 'platforms';
  
  // Visual effects
  hasWaterfall?: boolean;
  waterfallColor?: string;
  hasLavaFlow?: boolean;
  lavaFlowColor?: string;
  
  // Enemy configuration
  enemyTypes: string[];
  laserEnemyChance: number;
  enemySpawnRate: number;
  
  // Special features
  hasStars: boolean;
  starDensity: number;
  starColors: string[];
  hasAsteroids: boolean;
  hasPlanetInBackground: boolean;
  planetColor: string;
  planetSize: number;
}

// Generate 50 unique maps
export const MAPS: MapTheme[] = [
  // === SPACE MAPS (1-10) ===
  // Map 1: Classic cave
  {
    id: 1,
    name: "Deep Space",
    environment: 'space',
    backgroundColor1: '#050810',
    backgroundColor2: '#0a1020',
    backgroundColor3: '#100818',
    terrainColor: '#0a1a2a',
    terrainMidColor: '#1a3a4a',
    terrainGlowColor: '#2a8a9a',
    structureColor: '#2a4a5a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: false,
    hazeColor: '',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'cave',
    terrainMinHeight: 40,
    terrainMaxHeight: 120,
    structureChance: 0.12,
    structureTypes: ['building', 'pipe', 'tower'],
    enemyTypes: ['turret', 'drone', 'leech'],
    laserEnemyChance: 0.2,
    enemySpawnRate: 0.02,
    hasStars: true,
    starDensity: 200,
    starColors: ['#ffffff', '#aaccff', '#ffccaa'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 2,
    name: "Cyan Nebula",
    environment: 'nebula',
    backgroundColor1: '#040815',
    backgroundColor2: '#081828',
    backgroundColor3: '#0a2030',
    terrainColor: '#082028',
    terrainMidColor: '#104050',
    terrainGlowColor: '#00ffff',
    structureColor: '#1a4a6a',
    hasFog: true,
    fogColor: 'rgba(0, 255, 255, 0.03)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(0, 200, 255, 0.02)',
    hasNebula: true,
    nebulaColors: ['rgba(0, 100, 150, 0.05)', 'rgba(0, 200, 200, 0.03)'],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 30,
    terrainMaxHeight: 100,
    structureChance: 0.08,
    structureTypes: ['pipe', 'tower', 'crystal'],
    enemyTypes: ['drone', 'leech', 'sniper'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 150,
    starColors: ['#00ffff', '#80ffff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 3,
    name: "Magenta Storm",
    environment: 'nebula',
    backgroundColor1: '#100515',
    backgroundColor2: '#200a28',
    backgroundColor3: '#300f38',
    terrainColor: '#180820',
    terrainMidColor: '#301040',
    terrainGlowColor: '#ff00ff',
    structureColor: '#4a2a5a',
    hasFog: true,
    fogColor: 'rgba(255, 0, 255, 0.02)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(200, 0, 255, 0.03)',
    hasNebula: true,
    nebulaColors: ['rgba(150, 0, 150, 0.04)', 'rgba(255, 0, 200, 0.02)'],
    hasAurora: true,
    auroraColors: ['#ff00ff', '#ff00aa', '#aa00ff'],
    hasTerrain: true,
    terrainMinHeight: 50,
    terrainMaxHeight: 130,
    structureChance: 0.15,
    structureTypes: ['building', 'spire', 'crystal'],
    enemyTypes: ['turret', 'drone', 'bomber', 'tank'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.022,
    hasStars: true,
    starDensity: 180,
    starColors: ['#ff80ff', '#ffaaff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 4,
    name: "Asteroid Field",
    environment: 'asteroid',
    backgroundColor1: '#080808',
    backgroundColor2: '#101010',
    backgroundColor3: '#181818',
    terrainColor: '#1a1a1a',
    terrainMidColor: '#2a2a2a',
    terrainGlowColor: '#666666',
    structureColor: '#3a3a3a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: false,
    hazeColor: '',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['drone', 'missile', 'bomber'],
    laserEnemyChance: 0.15,
    enemySpawnRate: 0.025,
    hasStars: true,
    starDensity: 300,
    starColors: ['#ffffff', '#cccccc', '#888888'],
    hasAsteroids: true,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: false, // No terrain/ceiling, so no falling debris
    hasHazardousTerrain: false,
  },
  {
    id: 5,
    name: "Golden Expanse",
    environment: 'space',
    backgroundColor1: '#0a0805',
    backgroundColor2: '#1a1508',
    backgroundColor3: '#2a2010',
    terrainColor: '#1a1408',
    terrainMidColor: '#2a2410',
    terrainGlowColor: '#ffaa00',
    structureColor: '#4a3a1a',
    hasFog: true,
    fogColor: 'rgba(255, 170, 0, 0.02)',
    fogDensity: 0.3,
    hasHaze: true,
    hazeColor: 'rgba(255, 200, 50, 0.015)',
    hasNebula: true,
    nebulaColors: ['rgba(255, 150, 0, 0.03)', 'rgba(200, 100, 0, 0.02)'],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 35,
    terrainMaxHeight: 110,
    structureChance: 0.1,
    structureTypes: ['tower', 'pipe', 'building'],
    enemyTypes: ['turret', 'sniper', 'drone'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.019,
    hasStars: true,
    starDensity: 200,
    starColors: ['#ffdd88', '#ffcc66', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#ffaa44',
    planetSize: 80,
    hasFallingDebris: true, // Falling rocks in caves
    hasHazardousTerrain: true, // Cave walls are dangerous
  },
  {
    id: 6,
    name: "Void Between",
    environment: 'space',
    backgroundColor1: '#020204',
    backgroundColor2: '#040408',
    backgroundColor3: '#06060c',
    terrainColor: '#0a0a14',
    terrainMidColor: '#141428',
    terrainGlowColor: '#4444aa',
    structureColor: '#2a2a4a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(50, 50, 150, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 60,
    terrainMaxHeight: 140,
    structureChance: 0.06,
    structureTypes: ['tower', 'spire'],
    enemyTypes: ['leech', 'drone', 'sniper'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.015,
    hasStars: true,
    starDensity: 400,
    starColors: ['#aaaaff', '#8888ff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Falling debris
    hasHazardousTerrain: true, // Dangerous walls
  },
  {
    id: 7,
    name: "Electric Storm",
    environment: 'nebula',
    backgroundColor1: '#080810',
    backgroundColor2: '#101020',
    backgroundColor3: '#181830',
    terrainColor: '#0a0a1a',
    terrainMidColor: '#1a1a3a',
    terrainGlowColor: '#00ff88',
    structureColor: '#2a3a4a',
    hasFog: true,
    fogColor: 'rgba(0, 255, 136, 0.02)',
    fogDensity: 0.35,
    hasHaze: true,
    hazeColor: 'rgba(0, 200, 100, 0.025)',
    hasNebula: true,
    nebulaColors: ['rgba(0, 150, 100, 0.04)', 'rgba(0, 255, 150, 0.02)'],
    hasAurora: true,
    auroraColors: ['#00ff88', '#00ffaa', '#88ffaa'],
    hasTerrain: true,
    terrainMinHeight: 45,
    terrainMaxHeight: 115,
    structureChance: 0.14,
    structureTypes: ['pipe', 'tower', 'crystal'],
    enemyTypes: ['drone', 'sniper', 'bomber'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.02,
    hasStars: true,
    starDensity: 170,
    starColors: ['#88ffaa', '#aaffcc', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Electric storm debris
    hasHazardousTerrain: true, // Storm makes walls dangerous
  },
  {
    id: 8,
    name: "Red Giant Proximity",
    environment: 'space',
    backgroundColor1: '#100808',
    backgroundColor2: '#201010',
    backgroundColor3: '#301818',
    terrainColor: '#1a0a0a',
    terrainMidColor: '#2a1a1a',
    terrainGlowColor: '#ff4444',
    structureColor: '#4a2a2a',
    hasFog: true,
    fogColor: 'rgba(255, 68, 68, 0.02)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(200, 50, 50, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 55,
    terrainMaxHeight: 125,
    structureChance: 0.1,
    structureTypes: ['building', 'pipe', 'rock'],
    enemyTypes: ['turret', 'tank', 'drone'],
    laserEnemyChance: 0.25,
    enemySpawnRate: 0.021,
    hasStars: true,
    starDensity: 150,
    starColors: ['#ff8888', '#ffaaaa', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#ff4422',
    planetSize: 120,
  },
  {
    id: 9,
    name: "Binary System",
    environment: 'space',
    backgroundColor1: '#0a0508',
    backgroundColor2: '#140a10',
    backgroundColor3: '#1e0f18',
    terrainColor: '#120810',
    terrainMidColor: '#241018',
    terrainGlowColor: '#ff88ff',
    structureColor: '#3a2a3a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 100, 200, 0.015)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#ff88ff', '#88aaff', '#ffffff'],
    hasTerrain: true,
    terrainMinHeight: 40,
    terrainMaxHeight: 100,
    structureChance: 0.09,
    structureTypes: ['tower', 'building', 'spire'],
    enemyTypes: ['drone', 'missile', 'sniper'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 220,
    starColors: ['#ffaaff', '#aaaaff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#8888ff',
    planetSize: 60,
  },
  {
    id: 10,
    name: "Comet Trail",
    environment: 'space',
    backgroundColor1: '#050508',
    backgroundColor2: '#0a0a12',
    backgroundColor3: '#0f0f1c',
    terrainColor: '#0a0a15',
    terrainMidColor: '#151525',
    terrainGlowColor: '#88ffff',
    structureColor: '#2a3a4a',
    hasFog: true,
    fogColor: 'rgba(136, 255, 255, 0.015)',
    fogDensity: 0.25,
    hasHaze: false,
    hazeColor: '',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 35,
    terrainMaxHeight: 95,
    structureChance: 0.07,
    structureTypes: ['pipe', 'crystal', 'rock'],
    enemyTypes: ['drone', 'leech', 'bomber'],
    laserEnemyChance: 0.2,
    enemySpawnRate: 0.017,
    hasStars: true,
    starDensity: 350,
    starColors: ['#88ffff', '#aaffff', '#ffffff'],
    hasAsteroids: true,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  
  // === PLANET SURFACE MAPS (11-25) ===
  // Map 11: Open surface - Mars (no ceiling!)
  {
    id: 11,
    name: "Mars Surface",
    environment: 'planet',
    backgroundColor1: '#1a0a05',
    backgroundColor2: '#2a1008',
    backgroundColor3: '#3a180c',
    terrainColor: '#4a2010',
    terrainMidColor: '#6a3018',
    terrainGlowColor: '#ff6644',
    structureColor: '#5a3020',
    hasFog: true,
    fogColor: 'rgba(255, 100, 50, 0.03)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(200, 80, 40, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'surface', // Only ground, open sky!
    terrainMinHeight: 60,
    terrainMaxHeight: 150,
    structureChance: 0.18,
    structureTypes: ['rock', 'building', 'tower', 'dome'],
    enemyTypes: ['turret', 'tank', 'hostilePerson', 'sniper'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.022,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true,
    debrisType: 'rock',
  },
  {
    id: 12,
    name: "Ice World",
    environment: 'ice',
    backgroundColor1: '#0a1520',
    backgroundColor2: '#102535',
    backgroundColor3: '#18354a',
    terrainColor: '#1a3550',
    terrainMidColor: '#2a5070',
    terrainGlowColor: '#88ddff',
    structureColor: '#3a5a7a',
    hasFog: true,
    fogColor: 'rgba(136, 221, 255, 0.04)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(200, 230, 255, 0.05)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#88ddff', '#aaeeff', '#ccffff'],
    hasTerrain: true,
    terrainMinHeight: 50,
    terrainMaxHeight: 130,
    structureChance: 0.1,
    structureTypes: ['crystal', 'spire', 'rock'],
    enemyTypes: ['drone', 'sniper', 'turret'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 100,
    starColors: ['#ffffff', '#ddffff', '#aaddff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  // Map 13: Lava Fields - Surface with lava flows
  {
    id: 13,
    name: "Lava Fields",
    environment: 'lava',
    backgroundColor1: '#150505',
    backgroundColor2: '#250a08',
    backgroundColor3: '#35100c',
    terrainColor: '#2a1008',
    terrainMidColor: '#4a1810',
    terrainGlowColor: '#ff4400',
    structureColor: '#3a2010',
    hasFog: true,
    fogColor: 'rgba(255, 68, 0, 0.04)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(255, 100, 0, 0.05)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'surface', // Open lava fields
    terrainMinHeight: 70,
    terrainMaxHeight: 160,
    structureChance: 0.14,
    structureTypes: ['rock', 'pipe', 'tower', 'lavafall'],
    enemyTypes: ['turret', 'tank', 'bomber'],
    laserEnemyChance: 0.25,
    enemySpawnRate: 0.024,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasHazardousTerrain: true,
    hasLavaFlow: true,
    lavaFlowColor: '#ff4400',
  },
  {
    id: 14,
    name: "Toxic Swamp",
    environment: 'alien',
    backgroundColor1: '#0a1005',
    backgroundColor2: '#142008',
    backgroundColor3: '#1e300c',
    terrainColor: '#1a2a0a',
    terrainMidColor: '#2a4a14',
    terrainGlowColor: '#88ff00',
    structureColor: '#2a3a1a',
    hasFog: true,
    fogColor: 'rgba(136, 255, 0, 0.05)',
    fogDensity: 0.7,
    hasHaze: true,
    hazeColor: 'rgba(100, 200, 0, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 45,
    terrainMaxHeight: 110,
    structureChance: 0.16,
    structureTypes: ['pipe', 'tower', 'crystal'],
    enemyTypes: ['leech', 'drone', 'hostilePerson'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.02,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasHazardousTerrain: true, // Toxic terrain damages on contact
  },
  // Map 15: Crystal Caverns - ceiling only (stalactites!)
  {
    id: 15,
    name: "Crystal Caverns",
    environment: 'alien',
    backgroundColor1: '#08050a',
    backgroundColor2: '#100a15',
    backgroundColor3: '#180f20',
    terrainColor: '#140a18',
    terrainMidColor: '#281430',
    terrainGlowColor: '#ff00ff',
    structureColor: '#3a1a4a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 0, 255, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'ceiling', // Hanging crystals, open bottom
    terrainMinHeight: 80,
    terrainMaxHeight: 170,
    structureChance: 0.22,
    structureTypes: ['crystal', 'spire', 'crystal'],
    enemyTypes: ['drone', 'leech', 'bomber', 'missile'],
    laserEnemyChance: 0.55,
    enemySpawnRate: 0.0204, // 20% higher spawn rate
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true,
    debrisType: 'ice', // Falling crystals
  },
  {
    id: 16,
    name: "Desert Planet",
    environment: 'planet',
    backgroundColor1: '#1a1508',
    backgroundColor2: '#2a2510',
    backgroundColor3: '#3a3518',
    terrainColor: '#4a3a18',
    terrainMidColor: '#6a5a28',
    terrainGlowColor: '#ffcc44',
    structureColor: '#5a4a28',
    hasFog: true,
    fogColor: 'rgba(255, 200, 68, 0.025)',
    fogDensity: 0.35,
    hasHaze: true,
    hazeColor: 'rgba(255, 220, 100, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 55,
    terrainMaxHeight: 140,
    structureChance: 0.12,
    structureTypes: ['rock', 'building', 'tower'],
    enemyTypes: ['turret', 'hostilePerson', 'tank', 'sniper'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.02,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  // Map 17: Ocean World - underwater surface with waterfalls
  {
    id: 17,
    name: "Ocean World",
    environment: 'ocean',
    backgroundColor1: '#050a15',
    backgroundColor2: '#081528',
    backgroundColor3: '#0c203a',
    terrainColor: '#0a1828',
    terrainMidColor: '#142840',
    terrainGlowColor: '#00aaff',
    structureColor: '#1a3850',
    hasFog: true,
    fogColor: 'rgba(0, 170, 255, 0.03)',
    fogDensity: 0.45,
    hasHaze: true,
    hazeColor: 'rgba(0, 150, 255, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'ceiling', // Ocean cavern ceiling, open bottom
    terrainMinHeight: 40,
    terrainMaxHeight: 100,
    structureChance: 0.12,
    structureTypes: ['pipe', 'tower', 'dome', 'crystal'],
    enemyTypes: ['drone', 'bomber', 'leech', 'missile'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.0216, // 20% higher spawn rate
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasWaterfall: true,
    waterfallColor: '#00aaff',
  },
  {
    id: 18,
    name: "Twilight Zone",
    environment: 'planet',
    backgroundColor1: '#0a0810',
    backgroundColor2: '#141020',
    backgroundColor3: '#1e1830',
    terrainColor: '#180c20',
    terrainMidColor: '#281838',
    terrainGlowColor: '#aa88ff',
    structureColor: '#302848',
    hasFog: true,
    fogColor: 'rgba(170, 136, 255, 0.025)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(150, 100, 255, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#aa88ff', '#8866ff', '#cc99ff'],
    hasTerrain: true,
    terrainMinHeight: 50,
    terrainMaxHeight: 120,
    structureChance: 0.11,
    structureTypes: ['tower', 'spire', 'building'],
    enemyTypes: ['sniper', 'drone', 'turret'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.019,
    hasStars: true,
    starDensity: 120,
    starColors: ['#aa88ff', '#ccaaff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 19,
    name: "Volcanic Moon",
    environment: 'lava',
    backgroundColor1: '#100505',
    backgroundColor2: '#200808',
    backgroundColor3: '#300c0c',
    terrainColor: '#280808',
    terrainMidColor: '#401010',
    terrainGlowColor: '#ff6600',
    structureColor: '#381818',
    hasFog: true,
    fogColor: 'rgba(255, 102, 0, 0.035)',
    fogDensity: 0.55,
    hasHaze: true,
    hazeColor: 'rgba(255, 80, 0, 0.045)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'surface', // Open volcanic surface
    terrainMinHeight: 65,
    terrainMaxHeight: 155,
    structureChance: 0.13,
    structureTypes: ['rock', 'pipe', 'tower', 'lavafall'],
    enemyTypes: ['turret', 'tank', 'bomber', 'hostilePerson'],
    laserEnemyChance: 0.2,
    enemySpawnRate: 0.023,
    hasStars: true,
    starDensity: 80,
    starColors: ['#ffaa88', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#884422',
    planetSize: 150,
    hasHazardousTerrain: true, // Volcanic terrain damages on contact
    hasFallingDebris: true, // Falling volcanic rocks
    debrisType: 'lava',
    hasLavaFlow: true,
    lavaFlowColor: '#ff4400',
  },
  {
    id: 20,
    name: "Frozen Tundra",
    environment: 'ice',
    backgroundColor1: '#0c1218',
    backgroundColor2: '#142028',
    backgroundColor3: '#1c2e38',
    terrainColor: '#1a2830',
    terrainMidColor: '#2a4050',
    terrainGlowColor: '#aaddff',
    structureColor: '#3a4858',
    hasFog: true,
    fogColor: 'rgba(170, 221, 255, 0.05)',
    fogDensity: 0.65,
    hasHaze: true,
    hazeColor: 'rgba(200, 240, 255, 0.06)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#88ffaa', '#aaffcc', '#88ddff'],
    hasTerrain: true,
    terrainType: 'surface', // Open tundra
    terrainMinHeight: 55,
    terrainMaxHeight: 135,
    structureChance: 0.09,
    structureTypes: ['crystal', 'rock', 'spire'],
    enemyTypes: ['sniper', 'drone', 'turret'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.016,
    hasStars: true,
    starDensity: 90,
    starColors: ['#ffffff', '#ddffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Falling ice/hail
    debrisType: 'ice',
  },
  {
    id: 21,
    name: "Alien Jungle",
    environment: 'alien',
    backgroundColor1: '#051008',
    backgroundColor2: '#0a200c',
    backgroundColor3: '#0f3010',
    terrainColor: '#0a2008',
    terrainMidColor: '#143810',
    terrainGlowColor: '#44ff88',
    structureColor: '#1a3818',
    hasFog: true,
    fogColor: 'rgba(68, 255, 136, 0.035)',
    fogDensity: 0.55,
    hasHaze: true,
    hazeColor: 'rgba(50, 200, 100, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'surface', // Open jungle floor
    terrainMinHeight: 60,
    terrainMaxHeight: 145,
    structureChance: 0.2,
    structureTypes: ['pipe', 'tower', 'crystal', 'spire'],
    enemyTypes: ['leech', 'drone', 'hostilePerson', 'bomber'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.021,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 22,
    name: "Purple Haze Planet",
    environment: 'alien',
    backgroundColor1: '#0a0510',
    backgroundColor2: '#140a1a',
    backgroundColor3: '#1e0f25',
    terrainColor: '#180a18',
    terrainMidColor: '#281428',
    terrainGlowColor: '#cc66ff',
    structureColor: '#302040',
    hasFog: true,
    fogColor: 'rgba(204, 102, 255, 0.04)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(180, 80, 255, 0.05)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#cc66ff', '#aa44ff', '#ee88ff'],
    hasTerrain: true,
    terrainMinHeight: 50,
    terrainMaxHeight: 125,
    structureChance: 0.14,
    structureTypes: ['crystal', 'spire', 'tower'],
    enemyTypes: ['drone', 'sniper', 'leech'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.018,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 23,
    name: "Rust World",
    environment: 'planet',
    backgroundColor1: '#150a05',
    backgroundColor2: '#251408',
    backgroundColor3: '#351e0c',
    terrainColor: '#2a1408',
    terrainMidColor: '#4a2410',
    terrainGlowColor: '#ff8844',
    structureColor: '#4a3018',
    hasFog: true,
    fogColor: 'rgba(255, 136, 68, 0.03)',
    fogDensity: 0.45,
    hasHaze: true,
    hazeColor: 'rgba(200, 100, 50, 0.035)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 55,
    terrainMaxHeight: 140,
    structureChance: 0.16,
    structureTypes: ['building', 'pipe', 'rock', 'tower'],
    enemyTypes: ['turret', 'tank', 'hostilePerson'],
    laserEnemyChance: 0.25,
    enemySpawnRate: 0.02,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 24,
    name: "Night Side",
    environment: 'planet',
    backgroundColor1: '#050508',
    backgroundColor2: '#0a0a10',
    backgroundColor3: '#0f0f18',
    terrainColor: '#0a0a12',
    terrainMidColor: '#141420',
    terrainGlowColor: '#4488ff',
    structureColor: '#1a1a30',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(68, 136, 255, 0.015)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 45,
    terrainMaxHeight: 115,
    structureChance: 0.13,
    structureTypes: ['building', 'tower', 'pipe'],
    enemyTypes: ['sniper', 'drone', 'turret', 'bomber'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.019,
    hasStars: true,
    starDensity: 300,
    starColors: ['#ffffff', '#aaccff', '#ffccaa'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 25,
    name: "Storm Planet",
    environment: 'planet',
    backgroundColor1: '#080a10',
    backgroundColor2: '#101420',
    backgroundColor3: '#181e30',
    terrainColor: '#0c1018',
    terrainMidColor: '#1a2030',
    terrainGlowColor: '#88aaff',
    structureColor: '#2a3040',
    hasFog: true,
    fogColor: 'rgba(136, 170, 255, 0.035)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(100, 150, 255, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#88aaff', '#aaccff', '#ffffff'],
    hasTerrain: true,
    terrainType: 'surface', // Open storm-ravaged surface
    terrainMinHeight: 60,
    terrainMaxHeight: 150,
    structureChance: 0.11,
    structureTypes: ['tower', 'building', 'pipe'],
    enemyTypes: ['bomber', 'drone', 'turret', 'sniper'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.022,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Storm debris/metal
    debrisType: 'metal',
  },
  
  // === INDUSTRIAL / STATION MAPS (26-35) ===
  // Map 26: City level - tall skyscrapers!
  {
    id: 26,
    name: "Mega City",
    environment: 'city',
    backgroundColor1: '#080808',
    backgroundColor2: '#101010',
    backgroundColor3: '#181818',
    terrainColor: '#1a1a1a',
    terrainMidColor: '#2a2a2a',
    terrainGlowColor: '#00ff88',
    structureColor: '#3a3a3a',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(0, 255, 136, 0.015)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'city', // City with skyscrapers
    terrainMinHeight: 30,
    terrainMaxHeight: 60,
    structureChance: 0.35,
    structureTypes: ['skyscraper', 'skyscraper', 'building', 'antenna', 'dome'],
    enemyTypes: ['turret', 'drone', 'sniper', 'tank'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.02,
    hasStars: true,
    starDensity: 150,
    starColors: ['#ffffff', '#aaaaaa'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 27,
    name: "Mining Colony",
    environment: 'industrial',
    backgroundColor1: '#0a0808',
    backgroundColor2: '#141010',
    backgroundColor3: '#1e1818',
    terrainColor: '#1a1010',
    terrainMidColor: '#2a1818',
    terrainGlowColor: '#ffaa00',
    structureColor: '#3a2828',
    hasFog: true,
    fogColor: 'rgba(255, 170, 0, 0.02)',
    fogDensity: 0.3,
    hasHaze: true,
    hazeColor: 'rgba(200, 130, 0, 0.025)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'cave', // Underground mine tunnels
    terrainMinHeight: 65,
    terrainMaxHeight: 160,
    structureChance: 0.22,
    structureTypes: ['building', 'pipe', 'tower', 'rock'],
    enemyTypes: ['turret', 'hostilePerson', 'tank', 'drone'],
    laserEnemyChance: 0.25,
    enemySpawnRate: 0.021,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Falling rocks in mines
    debrisType: 'rock',
  },
  // Map 28: Flooded Shipyard - industrial waterCeiling
  {
    id: 28,
    name: "Flooded Shipyard",
    environment: 'ocean',
    backgroundColor1: '#050810',
    backgroundColor2: '#0a1520',
    backgroundColor3: '#0f1a28',
    terrainColor: '#0a1520',
    terrainMidColor: '#142030',
    terrainGlowColor: '#00aaff',
    structureColor: '#2a3848',
    hasFog: true,
    fogColor: 'rgba(0, 170, 255, 0.03)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(0, 150, 255, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'ceiling', // Industrial ceiling, open bottom
    terrainMinHeight: 60,
    terrainMaxHeight: 140,
    structureChance: 0.22,
    structureTypes: ['building', 'pipe', 'tower'],
    enemyTypes: ['drone', 'bomber', 'leech', 'missile'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.024, // 20% higher spawn rate
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasWaterfall: true,
    waterfallColor: '#00aaff',
  },
  {
    id: 29,
    name: "Refinery Complex",
    environment: 'industrial',
    backgroundColor1: '#0a0505',
    backgroundColor2: '#140a08',
    backgroundColor3: '#1e0f0c',
    terrainColor: '#180a08',
    terrainMidColor: '#281410',
    terrainGlowColor: '#ff4400',
    structureColor: '#382018',
    hasFog: true,
    fogColor: 'rgba(255, 68, 0, 0.025)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(200, 50, 0, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 80,
    terrainMaxHeight: 170,
    structureChance: 0.3,
    structureTypes: ['pipe', 'building', 'tower', 'pipe'],
    enemyTypes: ['turret', 'tank', 'hostilePerson', 'bomber'],
    laserEnemyChance: 0.2,
    enemySpawnRate: 0.023,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 30,
    name: "Defense Grid",
    environment: 'industrial',
    backgroundColor1: '#080810',
    backgroundColor2: '#101018',
    backgroundColor3: '#181820',
    terrainColor: '#0c0c14',
    terrainMidColor: '#181820',
    terrainGlowColor: '#ff0044',
    structureColor: '#282830',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 0, 68, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 70,
    terrainMaxHeight: 155,
    structureChance: 0.24,
    structureTypes: ['tower', 'building', 'pipe'],
    enemyTypes: ['turret', 'sniper', 'turret', 'tank', 'drone'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.025,
    hasStars: true,
    starDensity: 120,
    starColors: ['#ffffff', '#ff8888'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 31,
    name: "Cargo Bay",
    environment: 'industrial',
    backgroundColor1: '#080a08',
    backgroundColor2: '#101410',
    backgroundColor3: '#181e18',
    terrainColor: '#0c100c',
    terrainMidColor: '#181c18',
    terrainGlowColor: '#88ff88',
    structureColor: '#283028',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(136, 255, 136, 0.015)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 60,
    terrainMaxHeight: 145,
    structureChance: 0.2,
    structureTypes: ['building', 'building', 'pipe', 'tower'],
    enemyTypes: ['drone', 'hostilePerson', 'turret'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 100,
    starColors: ['#ffffff', '#aaffaa'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true, // Debris falls from ancient structures
  },
  {
    id: 32,
    name: "Power Core",
    environment: 'industrial',
    backgroundColor1: '#050510',
    backgroundColor2: '#0a0a18',
    backgroundColor3: '#0f0f20',
    terrainColor: '#080814',
    terrainMidColor: '#10101c',
    terrainGlowColor: '#00ffff',
    structureColor: '#202028',
    hasFog: true,
    fogColor: 'rgba(0, 255, 255, 0.025)',
    fogDensity: 0.35,
    hasHaze: true,
    hazeColor: 'rgba(0, 200, 255, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 75,
    terrainMaxHeight: 160,
    structureChance: 0.26,
    structureTypes: ['pipe', 'tower', 'building', 'pipe'],
    enemyTypes: ['sniper', 'drone', 'turret', 'bomber'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.02,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 33,
    name: "Waste Processing",
    environment: 'industrial',
    backgroundColor1: '#0a0a05',
    backgroundColor2: '#141408',
    backgroundColor3: '#1e1e0c',
    terrainColor: '#12120a',
    terrainMidColor: '#1e1e10',
    terrainGlowColor: '#aaff00',
    structureColor: '#2a2a18',
    hasFog: true,
    fogColor: 'rgba(170, 255, 0, 0.03)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(150, 200, 0, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 55,
    terrainMaxHeight: 135,
    structureChance: 0.18,
    structureTypes: ['pipe', 'pipe', 'building', 'tower'],
    enemyTypes: ['leech', 'drone', 'hostilePerson'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.019,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 34,
    name: "Communications Hub",
    environment: 'industrial',
    backgroundColor1: '#080508',
    backgroundColor2: '#100a10',
    backgroundColor3: '#180f18',
    terrainColor: '#0c080c',
    terrainMidColor: '#181018',
    terrainGlowColor: '#ff88ff',
    structureColor: '#282028',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 136, 255, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 65,
    terrainMaxHeight: 150,
    structureChance: 0.22,
    structureTypes: ['tower', 'tower', 'building', 'pipe'],
    enemyTypes: ['sniper', 'drone', 'turret'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.017,
    hasStars: true,
    starDensity: 140,
    starColors: ['#ff88ff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 35,
    name: "Research Lab",
    environment: 'industrial',
    backgroundColor1: '#050808',
    backgroundColor2: '#0a1010',
    backgroundColor3: '#0f1818',
    terrainColor: '#080c0c',
    terrainMidColor: '#101818',
    terrainGlowColor: '#44ffff',
    structureColor: '#202828',
    hasFog: true,
    fogColor: 'rgba(68, 255, 255, 0.02)',
    fogDensity: 0.3,
    hasHaze: true,
    hazeColor: 'rgba(50, 200, 200, 0.025)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 60,
    terrainMaxHeight: 140,
    structureChance: 0.2,
    structureTypes: ['building', 'pipe', 'tower', 'crystal'],
    enemyTypes: ['drone', 'leech', 'sniper', 'bomber'],
    laserEnemyChance: 0.55,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 110,
    starColors: ['#ffffff', '#aaffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },

  // === SPECIAL MAPS (36-50) ===
  {
    id: 36,
    name: "Wormhole Transit",
    environment: 'space',
    backgroundColor1: '#100510',
    backgroundColor2: '#200a20',
    backgroundColor3: '#300f30',
    terrainColor: '#180818',
    terrainMidColor: '#281028',
    terrainGlowColor: '#ff00ff',
    structureColor: '#381838',
    hasFog: true,
    fogColor: 'rgba(255, 0, 255, 0.04)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(200, 0, 255, 0.05)',
    hasNebula: true,
    nebulaColors: ['rgba(255, 0, 255, 0.06)', 'rgba(150, 0, 255, 0.04)'],
    hasAurora: true,
    auroraColors: ['#ff00ff', '#ff88ff', '#aa00ff'],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['drone', 'missile', 'bomber'],
    laserEnemyChance: 0.6,
    enemySpawnRate: 0.02,
    hasStars: true,
    starDensity: 400,
    starColors: ['#ff88ff', '#ffaaff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 37,
    name: "Quantum Field",
    environment: 'space',
    backgroundColor1: '#080810',
    backgroundColor2: '#101020',
    backgroundColor3: '#181830',
    terrainColor: '#0a0a14',
    terrainMidColor: '#141428',
    terrainGlowColor: '#00ff88',
    structureColor: '#1a1a30',
    hasFog: true,
    fogColor: 'rgba(0, 255, 136, 0.03)',
    fogDensity: 0.45,
    hasHaze: true,
    hazeColor: 'rgba(0, 200, 100, 0.035)',
    hasNebula: true,
    nebulaColors: ['rgba(0, 150, 100, 0.05)', 'rgba(0, 255, 150, 0.03)'],
    hasAurora: true,
    auroraColors: ['#00ff88', '#88ffaa', '#00ffaa'],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['drone', 'leech', 'missile'],
    laserEnemyChance: 0.55,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 350,
    starColors: ['#88ffaa', '#aaffcc', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  // Map 38: Abyssal Depths - deep ocean waterCeiling
  {
    id: 38,
    name: "Abyssal Depths",
    environment: 'ocean',
    backgroundColor1: '#020408',
    backgroundColor2: '#040810',
    backgroundColor3: '#060c18',
    terrainColor: '#0a1020',
    terrainMidColor: '#141830',
    terrainGlowColor: '#0088aa',
    structureColor: '#1a2838',
    hasFog: true,
    fogColor: 'rgba(0, 100, 150, 0.04)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(0, 80, 120, 0.05)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainType: 'ceiling', // Deep ocean cavern ceiling, open bottom
    terrainMinHeight: 70,
    terrainMaxHeight: 150,
    structureChance: 0.18,
    structureTypes: ['crystal', 'rock', 'pipe'],
    enemyTypes: ['drone', 'bomber', 'leech', 'missile'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.0252, // 20% higher spawn rate
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasWaterfall: true,
    waterfallColor: '#0088aa',
  },
  {
    id: 39,
    name: "Supernova Remnant",
    environment: 'nebula',
    backgroundColor1: '#0a0505',
    backgroundColor2: '#140a08',
    backgroundColor3: '#1e100c',
    terrainColor: '#140808',
    terrainMidColor: '#281010',
    terrainGlowColor: '#ff8800',
    structureColor: '#301818',
    hasFog: true,
    fogColor: 'rgba(255, 136, 0, 0.04)',
    fogDensity: 0.55,
    hasHaze: true,
    hazeColor: 'rgba(255, 100, 0, 0.05)',
    hasNebula: true,
    nebulaColors: ['rgba(255, 100, 0, 0.05)', 'rgba(255, 50, 0, 0.03)'],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['bomber', 'drone', 'missile'],
    laserEnemyChance: 0.3,
    enemySpawnRate: 0.024,
    hasStars: true,
    starDensity: 250,
    starColors: ['#ffaa88', '#ff8866', '#ffffff'],
    hasAsteroids: true,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 40,
    name: "Dimensional Rift",
    environment: 'space',
    backgroundColor1: '#050510',
    backgroundColor2: '#0a0a20',
    backgroundColor3: '#0f0f30',
    terrainColor: '#080818',
    terrainMidColor: '#101030',
    terrainGlowColor: '#8888ff',
    structureColor: '#181840',
    hasFog: true,
    fogColor: 'rgba(136, 136, 255, 0.035)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(100, 100, 255, 0.04)',
    hasNebula: true,
    nebulaColors: ['rgba(100, 100, 255, 0.05)', 'rgba(50, 50, 200, 0.03)'],
    hasAurora: true,
    auroraColors: ['#8888ff', '#aaaaff', '#ccccff'],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['leech', 'drone', 'sniper'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.017,
    hasStars: true,
    starDensity: 450,
    starColors: ['#aaaaff', '#ccccff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 41,
    name: "Gas Giant Orbit",
    environment: 'space',
    backgroundColor1: '#0a0810',
    backgroundColor2: '#141018',
    backgroundColor3: '#1e1820',
    terrainColor: '#100a14',
    terrainMidColor: '#1a1420',
    terrainGlowColor: '#ffaa88',
    structureColor: '#2a2030',
    hasFog: true,
    fogColor: 'rgba(255, 170, 136, 0.025)',
    fogDensity: 0.4,
    hasHaze: true,
    hazeColor: 'rgba(200, 150, 100, 0.03)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['drone', 'bomber', 'turret'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.019,
    hasStars: true,
    starDensity: 200,
    starColors: ['#ffffff', '#ffcc88'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#cc8844',
    planetSize: 200,
  },
  {
    id: 42,
    name: "Pulsar Beacon",
    environment: 'space',
    backgroundColor1: '#050810',
    backgroundColor2: '#0a1018',
    backgroundColor3: '#0f1820',
    terrainColor: '#080c14',
    terrainMidColor: '#10181c',
    terrainGlowColor: '#00ffff',
    structureColor: '#182028',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(0, 255, 255, 0.025)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#00ffff', '#88ffff', '#ffffff'],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['sniper', 'drone', 'missile'],
    laserEnemyChance: 0.6,
    enemySpawnRate: 0.02,
    hasStars: true,
    starDensity: 300,
    starColors: ['#88ffff', '#aaffff', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 43,
    name: "Radiation Zone",
    environment: 'space',
    backgroundColor1: '#0a0a05',
    backgroundColor2: '#141408',
    backgroundColor3: '#1e1e0c',
    terrainColor: '#10100a',
    terrainMidColor: '#1c1c10',
    terrainGlowColor: '#88ff00',
    structureColor: '#282818',
    hasFog: true,
    fogColor: 'rgba(136, 255, 0, 0.035)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(100, 200, 0, 0.04)',
    hasNebula: true,
    nebulaColors: ['rgba(100, 200, 0, 0.04)', 'rgba(150, 255, 0, 0.02)'],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['leech', 'drone', 'bomber'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.021,
    hasStars: true,
    starDensity: 180,
    starColors: ['#aaff88', '#ccffaa', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 44,
    name: "Antimatter Facility",
    environment: 'industrial',
    backgroundColor1: '#080508',
    backgroundColor2: '#100a10',
    backgroundColor3: '#180f18',
    terrainColor: '#0c080c',
    terrainMidColor: '#181018',
    terrainGlowColor: '#ff00aa',
    structureColor: '#281828',
    hasFog: true,
    fogColor: 'rgba(255, 0, 170, 0.03)',
    fogDensity: 0.45,
    hasHaze: true,
    hazeColor: 'rgba(200, 0, 150, 0.035)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 70,
    terrainMaxHeight: 160,
    structureChance: 0.25,
    structureTypes: ['pipe', 'building', 'tower', 'crystal'],
    enemyTypes: ['turret', 'sniper', 'tank', 'drone'],
    laserEnemyChance: 0.5,
    enemySpawnRate: 0.022,
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  // Map 45: Frozen Cavern - ice waterCeiling
  {
    id: 45,
    name: "Frozen Cavern",
    environment: 'ice',
    backgroundColor1: '#081018',
    backgroundColor2: '#102030',
    backgroundColor3: '#182840',
    terrainColor: '#0c1828',
    terrainMidColor: '#182840',
    terrainGlowColor: '#88ddff',
    structureColor: '#284050',
    hasFog: true,
    fogColor: 'rgba(136, 221, 255, 0.05)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(150, 220, 255, 0.06)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#88ddff', '#aaeeff', '#ffffff'],
    hasTerrain: true,
    terrainType: 'ceiling', // Ice cave ceiling, open bottom
    terrainMinHeight: 50,
    terrainMaxHeight: 130,
    structureChance: 0.24,
    structureTypes: ['crystal', 'crystal', 'spire'],
    enemyTypes: ['drone', 'bomber', 'leech', 'missile'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.0216, // 20% higher spawn rate
    hasStars: false,
    starDensity: 0,
    starColors: [],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
    hasFallingDebris: true,
    debrisType: 'ice',
    hasWaterfall: true,
    waterfallColor: '#88ddff',
  },
  {
    id: 46,
    name: "Solar Flare Zone",
    environment: 'space',
    backgroundColor1: '#100808',
    backgroundColor2: '#201010',
    backgroundColor3: '#301818',
    terrainColor: '#180c0c',
    terrainMidColor: '#281414',
    terrainGlowColor: '#ffff00',
    structureColor: '#382020',
    hasFog: true,
    fogColor: 'rgba(255, 255, 0, 0.03)',
    fogDensity: 0.5,
    hasHaze: true,
    hazeColor: 'rgba(255, 200, 0, 0.04)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: true,
    auroraColors: ['#ffff00', '#ffcc00', '#ff8800'],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['bomber', 'drone', 'missile'],
    laserEnemyChance: 0.35,
    enemySpawnRate: 0.023,
    hasStars: true,
    starDensity: 150,
    starColors: ['#ffff88', '#ffcc66', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#ffaa00',
    planetSize: 180,
  },
  {
    id: 47,
    name: "Dark Matter Cloud",
    environment: 'nebula',
    backgroundColor1: '#030305',
    backgroundColor2: '#050508',
    backgroundColor3: '#08080c',
    terrainColor: '#060608',
    terrainMidColor: '#0c0c10',
    terrainGlowColor: '#4444aa',
    structureColor: '#141418',
    hasFog: true,
    fogColor: 'rgba(68, 68, 170, 0.025)',
    fogDensity: 0.6,
    hasHaze: true,
    hazeColor: 'rgba(50, 50, 150, 0.03)',
    hasNebula: true,
    nebulaColors: ['rgba(40, 40, 120, 0.05)', 'rgba(60, 60, 180, 0.03)'],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['leech', 'drone', 'sniper'],
    laserEnemyChance: 0.55,
    enemySpawnRate: 0.016,
    hasStars: true,
    starDensity: 600,
    starColors: ['#8888aa', '#aaaacc', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 48,
    name: "Meteor Shower",
    environment: 'asteroid',
    backgroundColor1: '#080505',
    backgroundColor2: '#100a08',
    backgroundColor3: '#180f0c',
    terrainColor: '#100808',
    terrainMidColor: '#1c1010',
    terrainGlowColor: '#ff6644',
    structureColor: '#281818',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 102, 68, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: false,
    terrainMinHeight: 0,
    terrainMaxHeight: 0,
    structureChance: 0,
    structureTypes: [],
    enemyTypes: ['missile', 'bomber', 'drone'],
    laserEnemyChance: 0.2,
    enemySpawnRate: 0.025,
    hasStars: true,
    starDensity: 350,
    starColors: ['#ffaa88', '#ff8866', '#ffffff'],
    hasAsteroids: true,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 49,
    name: "Final Approach",
    environment: 'industrial',
    backgroundColor1: '#050505',
    backgroundColor2: '#0a0a0a',
    backgroundColor3: '#0f0f0f',
    terrainColor: '#0c0c0c',
    terrainMidColor: '#181818',
    terrainGlowColor: '#ff0000',
    structureColor: '#242424',
    hasFog: false,
    fogColor: '',
    fogDensity: 0,
    hasHaze: true,
    hazeColor: 'rgba(255, 0, 0, 0.02)',
    hasNebula: false,
    nebulaColors: [],
    hasAurora: false,
    auroraColors: [],
    hasTerrain: true,
    terrainMinHeight: 80,
    terrainMaxHeight: 180,
    structureChance: 0.3,
    structureTypes: ['building', 'tower', 'pipe', 'tower'],
    enemyTypes: ['turret', 'tank', 'sniper', 'bomber', 'drone'],
    laserEnemyChance: 0.45,
    enemySpawnRate: 0.026,
    hasStars: true,
    starDensity: 100,
    starColors: ['#ffffff', '#ff8888'],
    hasAsteroids: false,
    hasPlanetInBackground: false,
    planetColor: '',
    planetSize: 0,
  },
  {
    id: 50,
    name: "Victory Lane",
    environment: 'space',
    backgroundColor1: '#080510',
    backgroundColor2: '#100a18',
    backgroundColor3: '#180f20',
    terrainColor: '#0c0814',
    terrainMidColor: '#18101c',
    terrainGlowColor: '#ffcc00',
    structureColor: '#201828',
    hasFog: true,
    fogColor: 'rgba(255, 204, 0, 0.02)',
    fogDensity: 0.3,
    hasHaze: true,
    hazeColor: 'rgba(200, 150, 0, 0.025)',
    hasNebula: true,
    nebulaColors: ['rgba(255, 200, 0, 0.03)', 'rgba(255, 150, 0, 0.02)'],
    hasAurora: true,
    auroraColors: ['#ffcc00', '#ffaa00', '#ff8800'],
    hasTerrain: true,
    terrainMinHeight: 50,
    terrainMaxHeight: 130,
    structureChance: 0.15,
    structureTypes: ['building', 'tower', 'spire'],
    enemyTypes: ['drone', 'sniper', 'bomber'],
    laserEnemyChance: 0.4,
    enemySpawnRate: 0.018,
    hasStars: true,
    starDensity: 250,
    starColors: ['#ffcc88', '#ffaa66', '#ffffff'],
    hasAsteroids: false,
    hasPlanetInBackground: true,
    planetColor: '#4488ff',
    planetSize: 90,
  },
];

// Get map by id (1-indexed)
export function getMap(id: number): MapTheme {
  const index = Math.max(0, Math.min(id - 1, MAPS.length - 1));
  return MAPS[index];
}

// Get the effective terrain type for a map (handles legacy maps without terrainType)
export function getTerrainType(map: MapTheme): TerrainType {
  // If terrainType is explicitly set, use it
  if (map.terrainType) {
    return map.terrainType;
  }
  // Legacy fallback: use hasTerrain to determine type
  return map.hasTerrain ? 'cave' : 'openSpace';
}

// Get next map (loops back to 1 after 50)
export function getNextMapId(currentId: number): number {
  return currentId >= MAPS.length ? 1 : currentId + 1;
}

// Check if map requires Ultimate Edition (maps 21-50)
export function isMapLocked(mapId: number, hasUltimate: boolean): boolean {
  return mapId > 20 && !hasUltimate;
}

// The last free map ID (maps 1-20 are free)
export const LAST_FREE_MAP = 20;

// Check if transitioning to next map would start a new wave
export function isNewWave(currentId: number): boolean {
  return currentId >= MAPS.length;
}

// Map duration in scroll offset units
export const MAP_DURATION = 3000;

// Warp transition duration in frames
export const WARP_DURATION = 120; // Full warp for bonus levels (2 seconds)
export const QUICK_WARP_DURATION = 30; // Quick warp for regular levels (0.5 seconds)
